# Generated by Django 4.0 on 2023-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
