# Generated by Django 4.0 on 2023-04-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TextField(default='00:00:00'),
        ),
    ]
